### ISSUE TITLE
often stop unexpectedly [PlaneIndicator + NestedScrollView]

### ISSUE THREAD

**Issue by mzl1988** [gonuit/flutter-custom-refresh-indicator#24]
```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY╞════
The following assertion was thrown while dispatching notifications for IndicatorController:
Build scheduled during frame.
While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild
the widget tree.
This might be because setState() was called from a layout or paint callback. If a change is needed
to the widget tree, it should be applied as the tree is being built. Scheduling a change for the
subsequent frame instead results in an interface that lags behind by one frame. If this was done to
make your build dependent on a size measured at layout time, consider using a LayoutBuilder,
CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is
the desired effect, for example because this is an animation, consider scheduling the frame in a
post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to
trigger the animation.

When the exception was thrown, this was the stack:
#0      WidgetsBinding._handleBuildScheduled.<anonymous closure>
(package:flutter/src/widgets/binding.dart:747:9)
#1      WidgetsBinding._handleBuildScheduled (package:flutter/src/widgets/binding.dart:770:6)
#2      BuildOwner.scheduleBuildFor (package:flutter/src/widgets/framework.dart:2434:24)
#3      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4280:12)
#4      State.setState (package:flutter/src/widgets/framework.dart:1108:15)
#5      _AnimatedState._handleChange (package:flutter/src/widgets/transitions.dart:128:5)
#6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:308:24)
#7      IndicatorController.setIndicatorState
(package:custom_refresh_indicator/src/controller.dart:150:5)
#8      _CustomRefreshIndicatorState._start
(package:custom_refresh_indicator/src/custom_refresh_indicator.dart:293:16)
#9      _CustomRefreshIndicatorState._handleScrollEndNotification
(package:custom_refresh_indicator/src/custom_refresh_indicator.dart:212:9)
#10     _CustomRefreshIndicatorState._handleScrollNotification
(package:custom_refresh_indicator/src/custom_refresh_indicator.dart:283:14)
#11     Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4091:39)
#12     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:83:13)
#13     ScrollActivity.dispatchScrollEndNotification
(package:flutter/src/widgets/scroll_activity.dart:104:63)
#14     ScrollPosition.didEndScroll (package:flutter/src/widgets/scroll_position.dart:907:15)
#15     ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:876:9)
#16     _NestedInnerBallisticScrollActivity.applyNewDimensions
(package:extended_nested_scroll_view/src/extended_nested_scroll_view.dart:1676:14)
#17     ScrollPosition.applyNewDimensions (package:flutter/src/widgets/scroll_position.dart:623:15)
#18     _NestedScrollPosition.applyNewDimensions
(package:extended_nested_scroll_view/src/extended_nested_scroll_view.dart:1631:11)
#19     _ExtendedNestedScrollPosition.applyNewDimensions
(package:extended_nested_scroll_view/src/extended_nested_scroll_view_part.dart:261:11)
#20     ScrollPosition.applyContentDimensions
(package:flutter/src/widgets/scroll_position.dart:553:7)
#21     _ExtendedNestedScrollPosition.applyContentDimensions
(package:extended_nested_scroll_view/src/extended_nested_scroll_view_part.dart:273:18)
#22     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1493:20)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#39     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#40     RenderSliverFixedExtentBoxAdaptor.performLayout
(package:flutter/src/rendering/sliver_fixed_extent_list.dart:240:19)
#41     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#42     RenderSliverEdgeInsetsPadding.performLayout
(package:flutter/src/rendering/sliver_padding.dart:137:12)
#43     _RenderSliverFractionalPadding.performLayout
(package:flutter/src/widgets/sliver_fill.dart:167:11)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#45     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#46     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#47     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#54     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#56     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#60     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#61     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:56:11)
#62     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:896:45)
#63     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:931:32)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#65     RenderSliverFillRemainingWithScrollable.performLayout
(package:flutter/src/rendering/sliver_fill.dart:92:14)
#66     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#67     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#68     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#69     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#70     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707:7)
#71     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:879:18)
#72     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#73     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#74     RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:363:5)
#75     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#76     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#77     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#81     _invoke (dart:ui/hooks.dart:150:10)
#82     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#83     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 3 frames from dart:async)

The IndicatorController sending notification was:
  Instance of 'IndicatorController'
════════════════════════════════════════════════
```
![image](https://user-images.githubusercontent.com/11645762/149688859-052e3534-ff87-4290-8ade-37aa5d55144b.png)

![image](https://user-images.githubusercontent.com/11645762/149688795-750f5217-596a-4175-944c-e54cafa2830f.png)

**Comment by gonuit** [comment]
Thank you for opening the number and of course - sorry for the late reply.
I will check your problem in the coming days and let you know what can be done on my part.
___ 
I just updated your comment to make it more readable.
Try to use ```  instead of single ` in order to render the content as the code block.

**Comment by gonuit** [comment]
As you can see from the exception details, you are probably using the `setState` method when layouting/painting (inside the build method body).

Sometimes there is a need for such a thing. To get it to work, you need to schedule it as a post-frame job (post build/layout/paint). Here is the code:
```dart
SchedulerBinding.instance!
    .addPostFrameCallback((_) => setState(() {/* ... */}));
```
