### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by KubrickRubrik** [gonuit/flutter-custom-refresh-indicator#60]
An error occurs when using pullToRefreshKey.currentState?.hide() before onRefresh has completed.
```
'package:custom_refresh_indicator/src/custom_refresh_indicator.dart': Failed assertion: line 580 pos 12: 'controller.state.isLoading': is not true.
I/flutter ( 7139): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
I/flutter ( 7139): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
I/flutter ( 7139): #2      CustomRefreshIndicatorState._hideAfterRefresh (package:custom_refresh_indicator/src/custom_refresh_indicator.dart:580:12)
I/flutter ( 7139): #3      CustomRefreshIndicatorState._start (package:custom_refresh_indicator/src/custom_refresh_indicator.dart:574:13)
I/flutter ( 7139): <asynchronous suspension>
```

**Comment by gonuit** [comment]
Indeed, this might happen. I will work on this soon 👌
